source "https://rubygems.org"

gem "fastlane", "~> 2.219"

# Fastlane plugins
gem "fastlane-plugin-firebase_app_distribution"
gem "fastlane-plugin-versioning_android"

# Additional gems for Android development
gem "google-apis-androidpublisher_v3"
gem "google-apis-playcustomapp_v1"

# For better error handling and notifications
gem "slack-notifier"